server:
  port: 5001
spring:
  application:
    name: gateway
  cloud:
    client:
      ipAddress: 127.0.0.1
    gateway:
      routes: # 网关路由配置
        - id: resource_server1 # 路由id，自定义，只要唯一即可
          uri: http://127.0.0.1:4003 # 路由的目的地址 http 是固定地址
          predicates: # 路由断言
            - Path=/resource1/**
#          filters: # 过滤器
#            - AddRequestHeader=Truth, DueGin is freaking awesome! # 添加请求头
        - id: resource_server2
          uri: http://127.0.0.1:4002
          predicates:
            - Path=/resource2/**
    #            - After=2037-01-20T17:42:47.789+08:00[Asia/Shanghai]
        - id: authorization_server
          uri: http://127.0.0.1:3001
          predicates:
            - Path=/oauth/**
eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      #eurekaServers
      defaultZone: http://127.0.0.1:2001/eureka